name: Liquibase Test Harness

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

jobs:
  liquibase-test-harness:
    uses: liquibase/build-logic/.github/workflows/lth-docker.yml@DAT-14350
    secrets: inherit